# Generated by Django 5.2.13 on 2026-05-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('L', 'Литры'), ('T', 'Тонны')], default='L', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтвержден')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='app.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='app.station')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='app.station'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='app.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='app.station')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remainder', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fueltype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.dailyreport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'fuel_type'), name='uniq_fuel_per_report')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('date', 'station', 'employee'), name='uniq_report_per_employee_per_day'),
        ),
    ]
