# Generated by Django 5.2.13 on 2026-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fueltype',
            name='unit',
            field=models.CharField(choices=[('L', 'Литры'), ('T', 'Тонны'), ('KG', 'Килограммы'), ('M3', 'Кубометры'), ('ST', 'Штуки')], default='L', max_length=2),
        ),
    ]
